// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           14
// Async Callback (empty):               1
// Total number of exported functions:  17

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    cryptoland_tile
    (
        init => init
        upgrade => upgrade
        tokenIdFromKey => token_id_from_key
        keyFromTokenId => key_from_token_id
        mintTile => mint_tile
        claimTile => claim_tile
        setTilePrice => set_tile_price
        setMarketFeeBps => set_market_fee_bps
        setTreasuryReceiver => set_treasury_receiver
        withdraw => withdraw
        tilePrice => tile_price
        marketFeeBps => market_fee_bps
        treasury => treasury
        treasuryReceiver => treasury_receiver
        tileOwner => tile_owner
        totalMinted => total
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
