// @vitest-environment node
/**
 * Address display contract — CryptoLand
 * ======================================
 * `shortAddr()` is the single formatter behind every owner/wallet/seller string
 * in the UI, across 13 adapter families with wildly different address shapes.
 * A regression here is invisible on the EVM builds a developer runs locally and
 * only shows up on one non-EVM chain's bundle — the same failure mode
 * chains.test.js exists to catch for adapters.
 *
 * Fixtures are REAL rows generated by server/seed_chain.py, so the assertions
 * track what the seeded worlds actually contain.
 */

import { describe, it, expect } from 'vitest'
import { shortAddr, tinyAddr } from '../lib/addr.js'

// family → an address exactly as server/seed_chain.py emits it
const SEEDED = {
  evm:        '0x8f3a91c7d2e04b65a1f8092c3d47e6b5a09c1de2',
  solana:     '7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU',
  ton:        'EQBvW8Z5huBkMJYdnfAEM5JqTNkuWX3diqYENkWsIL0XggGG',
  aptos:      '0x' + 'a'.repeat(64),
  cardano:    'addr1qkxyvgufuyrxnp3cf4luf3vwmgmxpvxqk4pta85hrrfs85yw6qd4l',
  near:       'lumen5161.near',
  stellar:    'GA5ZSEJYB37JRC5AVCIA5MOP4RHTM335X2KGX3IHOJAPP5RE34K4KZVN',
  algorand:   '4UTIOJY252RTNQ6YBLQI4TVTRTRVXTDRBTHXKATCHWVK4EEN7I4YDKMZHN',
  multiversx: 'erd1qqqqqqqqqqqqqpgq0lzzvt2faev4upyf586tg38s84d7zsaj2jpqz9x0c3',
  radix:      'account_rdx129dyz5nzhxj2chlvug37z8rumhvsate0ew8gsxlcsne8t33mn4lvn',
  tezos:      'tz1VSUr8wwNhLAzempoch5d6hLRiTh8Cjcjb',
}

describe('shortAddr — every seeded chain family', () => {
  it('bounds every address to a width a panel can hold', () => {
    for (const [family, addr] of Object.entries(SEEDED)) {
      // 20 chars ≈ 140px at the 11–12px monospace the UI uses — fits the
      // narrowest surface (the 210px map tooltip) with room for its label.
      expect(shortAddr(addr).length, family).toBeLessThanOrEqual(20)
    }
  })

  it('keeps a tail so two addresses from one chain stay distinguishable', () => {
    // Seeded owners cluster, so head-only truncation collides constantly.
    const a = 'account_rdx129dyz5nzhxj2chlvug37z8rumhvsate0ew8gsxlcsne8t33mn4lvn'
    const b = 'account_rdx129dyz5nzhxj2chlvug37z8rumhvsate0ew8gsxlcsne8t33aaaaaa'
    expect(shortAddr(a)).not.toBe(shortAddr(b))
  })

  it('preserves the prefix that identifies the chain', () => {
    expect(shortAddr(SEEDED.cardano)).toMatch(/^addr1/)
    expect(shortAddr(SEEDED.radix)).toMatch(/^account_rdx/)
    expect(shortAddr(SEEDED.multiversx)).toMatch(/^erd1/)
    expect(shortAddr(SEEDED.tezos)).toMatch(/^tz1/)
    expect(shortAddr(SEEDED.ton)).toMatch(/^EQ/)
  })

  it('leaves the EVM shape exactly as it was before addr.js existed', () => {
    // 17 mainnet EVM builds ship this; changing it would be a visible regression.
    const a = SEEDED.evm
    expect(shortAddr(a)).toBe(a.slice(0, 6) + '…' + a.slice(-4))
  })

  it('never chops a human-readable name in the middle', () => {
    expect(shortAddr('lumen5161.near')).toBe('lumen5161.near')
    expect(shortAddr('cryptowhale.eth')).toBe('cryptowhale.eth')
    expect(shortAddr('a.b.near')).toBe('a.b.near')
  })

  it('returns a safe empty string for missing owners', () => {
    for (const v of [null, undefined, '', '   ']) expect(shortAddr(v)).toBe('')
  })

  it('leaves already-short values untouched', () => {
    expect(shortAddr('0xabc')).toBe('0xabc')
  })
})

describe('tinyAddr — 64px map sprite label', () => {
  it('fits the sprite for every family', () => {
    // 7px monospace on a 64px sprite ≈ 15 characters.
    for (const [family, addr] of Object.entries(SEEDED)) {
      expect(tinyAddr(addr, 10).length, family).toBeLessThanOrEqual(14)
    }
  })

  it('still shows a NEAR/ENS name rather than a hash fragment', () => {
    expect(tinyAddr('lumen5161.near', 10)).toBe('lumen5161.near')
  })
})
