"""
tile_pricing.py — what a tile costs, decided by the server.

GENERATED by scripts/gen-tile-pricing.mjs from src/lib/tiles.js. Do not edit by
hand: edit the JS and re-run the generator, or the map will quote one price and
the server will charge another.

Why this exists at all: the native-wallet purchase path (POST /chain/quote) must
price a tile without believing anything the browser says. The NOWPayments path
stores `price_usd` from a client-supplied field, so a crafted request buys any
tile for any amount; that hole is not repeated here.

Kept deliberately dependency-free so it imports under pytest with no app context.
"""

PURCHASE_ZOOM = 14
GRID_N = 16384
TOTAL_TILES = GRID_N * GRID_N
MIN_TILE_PRICE_USD = 12

# (lng_min, lng_max, lat_min, lat_max, base, spread) — first match wins, exactly
# as the JS loop does. Order is load-bearing: Tokyo metro sits inside Japan.
GEO_REGIONS = [
    (-125, -114, 32, 50, 48, 28),
    (-80, -68, 38, 46, 50, 26),
    (-11, 3, 49, 61, 46, 24),
    (3, 11, 46, 54, 48, 22),
    (6, 18, 47, 55, 44, 22),
    (4, 32, 55, 72, 44, 20),
    (-5, 8, 43, 51, 42, 22),
    (103, 105, 1, 2, 52, 20),
    (130, 142, 33, 37, 44, 22),
    (138, 141, 35, 36, 56, 18),
    (-105, -75, 29, 48, 36, 20),
    (-100, -70, 43, 52, 34, 18),
    (-10, 5, 36, 44, 32, 18),
    (7, 19, 37, 47, 32, 18),
    (14, 24, 47, 55, 30, 16),
    (51, 57, 22, 26, 42, 22),
    (144, 154, -38, -27, 38, 20),
    (126, 130, 35, 38, 38, 18),
    (34, 36, 29, 34, 34, 16),
    (35, 44, 55, 61, 26, 14),
    (26, 36, 37, 42, 24, 14),
    (113, 122, 22, 41, 28, 16),
    (43, 58, 22, 32, 28, 14),
    (-48, -40, -24, -18, 26, 14),
    (20, 30, 42, 48, 22, 12),
    (21, 28, 54, 60, 26, 12),
    (20, 27, 35, 42, 24, 12),
    (-100, -96, 19, 26, 22, 12),
    (-60, -56, -35, -32, 22, 10),
    (130, 142, 31, 45, 36, 16),
    (27, 180, 50, 75, 16, 10),
    (22, 40, 46, 53, 18, 10),
    (72, 88, 18, 29, 20, 12),
    (98, 113, 22, 42, 18, 10),
    (98, 109, 5, 21, 18, 10),
    (106, 115, -9, -5, 16, 8),
    (25, 37, 22, 32, 18, 10),
    (18, 32, -35, -25, 20, 10),
    (-78, -65, -56, 8, 18, 8),
    (-10, 15, 28, 38, 16, 8),
    (50, 90, 36, 56, 14, 8),
    (60, 78, 23, 37, 14, 8),
    (88, 93, 20, 27, 14, 6),
    (117, 127, 5, 20, 16, 8),
    (-18, 52, -35, 16, 12, 6),
    (-90, -60, 8, 24, 12, 6),
    (-82, -35, -60, 12, 12, 6),
    (92, 107, 9, 29, 12, 6),
    (130, 180, -50, 20, 12, 6),
    (88, 125, 42, 55, 12, 6),
    (-180, 180, 72, 90, 12, 4),
    (-180, 180, -90, -60, 12, 4),
]

# Ocean / unclassified, matching geoRegion()'s fallback.
DEFAULT_REGION = (12, 6)

import math


def tile_nw(tx: int, ty: int, z: int = PURCHASE_ZOOM):
    """Tile NW corner -> (lng, lat). Mirrors tileNW() in src/lib/tiles.js."""
    n = 2.0 ** z
    lng = tx / n * 360.0 - 180.0
    lat_rad = math.atan(math.sinh(math.pi * (1.0 - 2.0 * ty / n)))
    return lng, lat_rad * 180.0 / math.pi


def geo_region(lng: float, lat: float):
    """-> (base, spread). Mirrors geoRegion() in src/lib/tiles.js."""
    for lng_min, lng_max, lat_min, lat_max, base, spread in GEO_REGIONS:
        if lng_min <= lng < lng_max and lat_min <= lat < lat_max:
            return base, spread
    return DEFAULT_REGION


def tile_base_price(tx: int, ty: int) -> float:
    """
    USD price of a tile before market events. Mirrors tileBasePrice().

    The hash uses >>> 0 in JS (unsigned 32-bit); Python ints are unbounded, so
    the & 0xFFFFFFFF is what keeps the two in step on large coordinates.
    """
    lng, lat = tile_nw(tx, ty, PURCHASE_ZOOM)
    base, spread = geo_region(lng, lat)
    h = ((tx * 1619 + ty * 2971) & 0xFFFFFFFF) % 1000 / 1000.0
    price = base + h * spread
    return round(max(MIN_TILE_PRICE_USD, price) + 1e-9, 2)


def scarcity_multiplier(sold_count: int) -> float:
    """
    Tiles get more expensive as the world fills. Mirrors the client's
    `1 + sold / TOTAL_TILES * 3` in PurchasePanel.jsx.
    """
    return 1.0 + (max(0, sold_count) / TOTAL_TILES) * 3.0
