[package]
name = "cryptoland"
version = "0.1.0"
authors = []

[addresses]
cryptoland = "_"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "aptos-node-v1.9.7"
subdir = "aptos-move/framework/aptos-framework"
